baseURL = "http://samwalkow.github.io"
languageCode = "en-us"
title = "Sam Walkow Website"
theme = "swift"
copyright = ""
publishdir = "samwalkow/github.io"

[Author]
name = "Sam Walkow"

[Taxonomies]
tag = "tags"
series = "series"
series-desc = "series-desc"

[Permalinks]
blog = "/:year/:month/:filename/"
code = "/:filename/"

[params]
description = "Site description"
twitter = "https://twitter.com/samwalkow"
github = "https://github.com/samwalkow"
